version: '3.2'

services:
  etcd:
    image: bitnami/etcd:3.3.10
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
    volumes:
      - etcd_data:/bitnami
volumes:
  etcd_data:
    driver: local